# file: linux-sensors/tasks/main.yaml
# synopsis: install hardware sensor modules and tools
---
- name: Install hardware sensor packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sensor_packages }}"

- name: Load sensor modules
  block:
    - name: Load drivetemp module
      community.general.modprobe:
        name: drivetemp
        state: present
    - name: Make drivetemp module permanent
      ansible.builtin.lineinfile:
        path: /etc/modules
        regexp: '^drivetemp'
        line: drivetemp
    - name: Load coretemp module
      community.general.modprobe:
        name: coretemp
        state: present
    - name: Make coretemp module permanent
      ansible.builtin.lineinfile:
        path: /etc/modules
        regexp: '^coretemp'
        line: coretemp
